### ISSUE TITLE
ModuleNotFoundError: No module named 'tale.llm'

### ISSUE THREAD

**Issue by Jake36921** [neph1/LlamaTale#76]
(venv) (base) PS A:\etc\LlamaTale-0.26.3\scripts> python -m tale.main -g A:\etc\LlamaTale-0.26.3\stories\anything
Traceback (most recent call last):
  File "E:\etc\Anaconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\etc\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "A:\etc\LlamaTale-0.26.3\venv\lib\site-packages\tale\main.py", line 55, in <module>
    run_from_cmdline(sys.argv[1:])
  File "A:\etc\LlamaTale-0.26.3\venv\lib\site-packages\tale\main.py", line 45, in run_from_cmdline
    driver.start(args.game)
  File "A:\etc\LlamaTale-0.26.3\venv\lib\site-packages\tale\driver.py", line 237, in start
    import story
  File "A:\etc\LlamaTale-0.26.3\stories\anything\.\story.py", line 9, in <module>
    from tale.llm.llm_ext import DynamicStory
ModuleNotFoundError: No module named 'tale.llm'

**Comment by neph1** [comment]
Hey! Try:
`python -m stories.anything.story` in the main LlamaTale folder.
Add `--web` if you want to run in a browser

**Comment by Jake36921** [comment]
Thanks.
